apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-bamoe-pvc
  namespace: bamoe-k8s
spec:
  storageClassName: ""
  volumeName: postgres-bamoe-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
