apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-bamoe-pvc
  namespace: bamoe-k8s
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
