apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-bamoe-pvc
  namespace: bamoe-ns
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 5Gi
